server/src/main/java/com/codestates/mainproject/domain/article/dto/ArticlePatchDto.java
server/src/main/java/com/codestates/mainproject/validator/NotSpaceInteger.java
server/src/main/java/com/codestates/mainproject/validator/NotSpaceIntegerValidator.java

#8 fix: 게시글 patchDto 유효성 검증 변경 및 Custom Validator 추가

---

server/build.gradle
server/src/docs/asciidoc/index.adoc
server/src/docs/asciidoc/overview.adoc
server/src/main/java/com/codestates/mainproject/domain/member/controller/MemberController.java
server/src/main/resources/static/docs/index.html
server/src/main/resources/static/docs/overview.html

api html생성

---

server/src/main/java/com/codestates/mainproject/advice/GlobalExceptionAdvice.java
server/src/main/java/com/codestates/mainproject/domain/answer/entity/Answer.java
server/src/main/java/com/codestates/mainproject/domain/answer/service/AnswerService.java
server/src/main/java/com/codestates/mainproject/domain/article/service/ArticleService.java
server/src/main/java/com/codestates/mainproject/domain/comment/service/CommentService.java
server/src/main/java/com/codestates/mainproject/domain/hashtag/service/HashtagService.java
server/src/main/java/com/codestates/mainproject/domain/interest/service/InterestService.java
server/src/main/java/com/codestates/mainproject/domain/member/service/MemberService.java
server/src/main/java/com/codestates/mainproject/domain/skill/service/SkillService.java
server/src/main/java/com/codestates/mainproject/exception/BusinessLogicException.java
server/src/main/java/com/codestates/mainproject/exception/ExceptionCode.java
server/src/main/java/com/codestates/mainproject/response/ErrorResponse.java
server/src/main/resources/application.yml
server/src/main/resources/data.sql
server/src/test/java/com/codestates/mainproject/domain/answer/controller/AnswerControllerTest.java
server/src/test/java/com/codestates/mainproject/domain/comment/controller/CommentControllerTest.java

Dev be feat/issue#13

---

client/src/assets/style/GlobalVariable.js
client/src/components/InputTitle.js

- 게시글 작성/수정 페이지에 사용되는 제목 입력란 컴포넌트입니다! 
- props로 placeholder, value, onChange를 받도록 했으니 활용하실 때 참고해주세요. 
- GlobalVariable에 purple-medium 컬러를 추가했습니다.
- css 부분은 폰트 관련 부분 말고는 기본 input창과 동일해서 활용하실 수 있을 것 같습니다!☺️

Feat: 제목 입력란 컴포넌트 구현

---

server/build.gradle
server/src/main/java/com/codestates/mainproject/domain/article/entity/Article.java
server/src/main/java/com/codestates/mainproject/domain/article/entity/Heart.java
server/src/main/java/com/codestates/mainproject/domain/member/controller/MemberController.java
server/src/main/java/com/codestates/mainproject/domain/member/dto/EmailDto.java
server/src/main/java/com/codestates/mainproject/domain/member/dto/VerifyNameDto.java
server/src/main/java/com/codestates/mainproject/domain/member/service/MemberService.java
server/src/main/java/com/codestates/mainproject/email/config/EmailConfig.java
server/src/main/java/com/codestates/mainproject/email/service/EmailService.java
server/src/main/java/com/codestates/mainproject/exception/ExceptionCode.java
server/src/main/java/com/codestates/mainproject/redis/RedisConfig.java
server/src/main/java/com/codestates/mainproject/redis/RedisDao.java
server/src/main/java/com/codestates/mainproject/security/auth/jwt/JwtTokenizer.java
server/src/main/java/com/codestates/mainproject/security/config/SecurityConfiguration.java
server/src/main/resources/application-aws.yml
server/src/main/resources/application-server.yml
server/src/main/resources/application.yml
server/src/main/resources/static/docs/index.html
server/src/main/resources/static/docs/overview.html
server/src/test/java/com/codestates/mainproject/domain/member/controller/MemberControllerTest.java

#27 feat: 이메일 인증 기능 구현 완료 및 일부 코드 리팩토링

---

client/package.json
client/src/atom/atom.js
client/src/components/BackButton.js
client/src/components/Calendar.js
client/src/components/Header.js
client/src/components/InputBody.js
client/src/components/InputHashTag.js
client/src/components/InputTitle.js
client/src/components/InterestSelect.js
client/src/components/NumberSelect.js
client/src/components/SkillStackSelect.js
client/src/pages/ArticleWrite.js
client/src/utils/getFormatDate.js

#69 
```
변경한 파일이 정말... 많습니다..ㅎㅎ
그래서 PR을 최대한 자세히 작성해봤습니다!
PR 내용과 비교해서 보시면 코드를 이해하시기 쉬우실 것 같습니다!...ㅎ...
```
_<유효성검사 로직>
패이지가 처음 로딩되었을 떄, 아무 클릭이 없다면 유효성 검사 문구가 보이지 않습니다.
작성하기 버튼을 눌렀을 때, 유효성검사를 통해 각 요소들에게 유효성 검사문구가 보이게 됩니다.
각 요소들을 클릭해 통과했다가, 다시 통과하지 못하면 그때 해당 요소의 유효성 검사문구가 보입니다._
- package.json
- 토스트UI 라이브러리 설치하고 에러 해결하느라 수정사항이 발생했습니다.
- atom (상태 선언 파일)
- 게시글 제목, 본문의 value를 저장할 상태 선언
- 게시글 유효성 검사 관련 상태 추가
(CheckState로 끝나는 상태들은 전부 유효성 검사를 위한 상태입니다.)
- BackButton (뒤로가기 버튼)
- 뒤로가기 버튼의 배경색이 흰색으로 되어있어 배경을 배경색으로 설정
- 아이콘을 중앙에 위치
- 크기 고정
- Calendar (날짜 선택 컴포넌트)
- CSS를 인원 선택란과 비슷하게 수정
- 날짜를 클릭하면 날짜체크상태가 true로 변하면서 유효성 검사를 통과
- Header (헤더)
- 유효성 검사가 나타나있는 상태로 헤더를 통해 전체 게시글 화면에 갔다가 
다시 글쓰기버튼으로 이동해오면 계속 유효성 검사 문구가 계속 뜨는 이슈가 있어
헤더에서 글쓰기 버튼 클릭시 유효성 검사 상태를 초기화 시켜주었습니다.
- InputBody (본문 입력 컴포넌트 - 에디터 라이브러리 …

feat: 게시글 작성 페이지 구현

---

client/src/pages/Profile.js

뭔가 약간 실수가 있었는데 수정해서 잘되는 거 확인했고 감사합니다 세비님

Feat : 프로필 상세보기 수정

---

client/src/App.js
client/src/assets/style/GlobalVariable.js
client/src/components/BackButton.js
client/src/components/Comment.js
client/src/components/InterestView.js
client/src/components/Recomment.js
client/src/components/SkillStackView.js
client/src/components/SwitchToggle.js
client/src/pages/ArticleDetail.js

다들 열심히 설명글을 적어주셔서 저도 최대한 자세히 작성해보려 노력했습니다!ㅎㅎ
생각보다 고쳐야 할 부분도 많고 추가해야 할 부분도 많네요..🤣🤣
아무래도 기능 구현이 저에게 어려웠기 때문에 제가 놓친 부분이나 생각 못한 부분들이 있을 것 같으니 더 좋은 코드 작성 법이나 아이디어가 있으시다면 언제든 알려주시면 감사하겠습니다!
**- App.js**
- profile 컴포넌트 라우트 패스에 id 파라미터를 추가하였습니다.
**- Comment.js**
- 댓글 컴포넌트 입니다. 로그인 기능 구현 후 토큰 부분이 수정되어야 합니다.
- 댓글 조회,생성,수정,삭제 기능 모두 가능하지만 소소한 버그와 추가 구현할 기능이 남아있습니다..😅 
✅ 댓글을 수정하면 새로고침을 해야 수정한 데이터가 렌더링 됩니다.. 
✅ 댓글 등록을 엔터로 하게 되면, 댓글 등록 후 인풋창 초기화 될 수 있도록 추가 구현 해야 합니다.
✅ 유효성 검사도 따로 추가 구현 하면 좋을 것 같습니다!
**- InterestView.js**
- 폰트사이즈를 Proprs 로 바꿀 수 있도록 수정하였으며, 마진 간격 조절하였습니다.
**- ReComment.js**
- 대댓글 컴포넌트 입니다. 
- 현재 조회만 가능하며, 나머지 CUD 기능이 빠져 있는 상태입니다. 
→ 추후 시간적 여유가 있을 때 도전해 보아야 할 것 같습니다..!!!🥲🥲
**- SkillStackView.js**
- 폰트사이즈,마진 등 디자인만 일부 수정하였습니다.
**- ArticleDetail.js**
- Comment.js 와 ReComment.js 컴포넌트가 하단에 있어 …

Feat: 게시글 상세보기 페이지 구현

---

client/src/atom/atom.js
client/src/pages/ArticleDetail.js
client/src/pages/Profile.js
client/src/utils/getSkills.js

#86 
- atom
- 키값에 오타가 있길래 수정했습니다!
- ArticleDetail 페이지
- 기술스택보기란에 기술스택이 마지막 하나만 표시되는 오류가 있었지만, 게시글 수정을 하며 해결한 로직을 적용해 수정했습니다.
- 게시글 수정, 삭제버튼은 currentUser의 memberId와 게시글의 작성자인 memberId가 같을 때만 보이도록 수정했습니다.
- currentUser의 memberId와 게시글의 작성자인 memberId가 같을 때만 
모집 토글 버튼으로 모집 상태를 수정할 수 있도록 수정했습니다.
권한이 없다면 alert으로 수정권한이 없다는 문구가 나오도록 처리했습니다!

refactor: 기술스택 보기란 정보받기, 수정삭제 작성자만 보이도록 리팩토링

---

client/src/App.js
client/src/atom/atom.js
client/src/components/Comment.js
client/src/components/Header.js
client/src/components/ProfileCard.js
client/src/pages/ArticleDetail.js
client/src/pages/ArticleEdit.js
client/src/pages/ArticleWrite.js
client/src/pages/Main.js
client/src/pages/MyPage.js
client/src/pages/MyPageEdit.js
client/src/pages/Profile.js

- App.js
[design: 170px 마진 반응형 수정]
- atom.js
[style: 공백 삭제]
- Comment.js
[design: 댓글부분 최소 넖이 설정]
- Header.js
[design: 크기 조절에 따라 헤더 수정]
- ProfileCard.js
[design: 글자 색 흰색에서 검정으로 수정]
- ArticleDetail.js
[design, feat: 상세페이지 반응형 수정 및 작성자에 따른 마이페이지, 프로필 연결]
- ArticleWrite.js, ArticleEdit.js
[design: 게시글 수정/작성페이지 반응형 구현]
- Mypage.js, MypageEdit.js, Profile.js
[design: 마이페이지, 수정, 프로필 페이지 바로 스크롤 안생기도록 수정]

design: 반응형 구현

---

client/package.json
client/src/assets/toast.js
client/src/atom/atom.js
client/src/components/ContentViewer.js
client/src/components/LevelSelect.js
client/src/pages/ArticleDetail.js
client/src/pages/ArticleEdit.js
client/src/pages/ArticleWrite.js
client/src/pages/LogIn.js
client/src/pages/MyPage.js
client/src/pages/MyPageEdit.js
client/src/pages/SignUp.js

**ContentViewer.js**
- 토스트 UI 뷰어를 적용하기 위해 컴포넌트를 생성했습니다.
**toast.js**
- 토스트 알럿창 구현을 위해 함수 형태로 만들어 asset 폴더에 파일을 생성했습니다.
- 원래 회의 땐 react-toastify 를 이용해서 하기로 했었는데요, 계속 적용이 안되어서 구글링 해보니까  ToastContainer 라는 컴포넌트를 사용하는 버튼 아래에 리턴 해주니 적용되어 창이 보이더라고요! 모든 파일에 해당 컴포넌트를 적용하는게 불필요하게 느껴져서 새로운 라이브러리를 찾아서 SweetAlert2 를 적용하였습니다. 
- 사용 방법은 toast.js 에서 확인하실 수 있는 함수를 용도따라 사용하시면 될 것 같고, 파라미터에 메세지를 적어주시면 적용 됩니다!
- window.confirm 창 대체로 notiConfirm()을 사용하실 수 있는데, 로직 구현은 안되어 있으니 사용하신다면 처리해서 해주시면 될 것 같습니다!
- 혹시 적용 안된 페이지가 있으시다면, toast.js 에서 사용하시면 됩니다!

Feat: 토스트UI 뷰어 적용,SweetAlert2 라이브러리 적용

---

client/src/atom/atom.js
client/src/components/Header.js
client/src/pages/ArticleDetail.js
client/src/pages/ArticleEdit.js
client/src/pages/ArticleWrite.js
client/src/pages/LogIn.js
client/src/pages/MyPage.js
client/src/pages/MyPageEdit.js

Feat/#082 로그인 구현

---

client/src/components/ContentViewer.js
client/src/components/InputBody.js

#102 
- 사진 버튼 추가
- 토스트 UI적용된 게시글 상세보기 반응형 수정

feat: 토스트 UI 사진 업로드 및 반응형 수정

---

client/src/components/Header.js
client/src/components/InputHashTag.js
client/src/components/ProfileCard.js
client/src/pages/ArticleDetail.js
client/src/pages/ArticleEdit.js
client/src/pages/ArticleWrite.js
client/src/pages/MyPage.js
client/src/pages/Profile.js

#105 
오류는 currentUser.memberId는 스트링, 비교군은 넘버형이라 인식하지 못해 오류가 나는 거였습니다!
Number형으로 바꿔주면서 오류를 해결했습니다.
- Header
[feat: 헤더 글작성 버튼 로그인시 접근 가능 구현]
- InputHashTag
[refactor: 해시태그 공백 입력 시, 안내창 라이브러리 적용]
- ProfileCard
[fix: 수정, 탈퇴버튼 본인에게만 보이도록 버그 수정]
- ArticleDetail
[fix: 게시글 수정, 삭제 버튼 본인에게만 보이도록 버그 수정]
- ArticleEdit, ArticleWrite
[feat: 글 등록/ 수정 시 안내창 구현]
- Mypage
[refactor: 탈퇴하기 로직 수정]
[design: 마이페이지 반응형 구현]
- Profile
[design: 프로필페이지 반응형 구현]

fix: 작성자만 버튼 보이기 기능 버그 수정 및 반응형 수정

---

client/src/components/Comment.js
client/src/components/ContentViewer.js
client/src/components/SwitchToggle.js
client/src/pages/ArticleDetail.js

**SwitchToggle.js**
리액트에서  <input type="checkbox"> 를 쓸 때, 이벤트 핸들러를 onChange 대신 onClick으로 핸들링하면서 생긴 오류를 readonly 키워드를 붙여 해결하였습니다.
**ArticleDetail.js /  **
로그인 한 게시글 작성자만 모집여부 토글 스위치를 바꿀 수 있도록 변경하였습니다.
✅ 좋아요 기능은 오늘 중으로 해보도록 하겠습니다!
**Comment.js**
로그인한 댓글 작성자에게만 수정하기/삭제하기 버튼이 보이고, 클릭할 수 있도록 변경하였습니다.
**ContentViewer.js**
세비님이 수정하셨던 반응형 코드를 적용하였습니다.

Fix: 로그인 상태에 따른 로직 변경

---

client/src/assets/style/GlobalStyle.js
client/src/components/Header.js
client/src/pages/LogIn.js

Feat/#107 로그인 버그 수정

---

client/src/pages/LogIn.js

feat : 엔터키로 로그인 구현

---

client/src/pages/SignUp.js

- 회원가입 페이지의 내용이 유효성 검사 상태를 제대로 반영하지 못하고 있는 버그를 수정했습니다! 
`다른 state를 반영하고 있는 경우도 있었고, 사라져야 하는 경우를 제대로 검사하지 못하고 있었습니다ㅠ. 우선은 props로 넘겨줄 때 삼항연산자로 검사해 메시지를 고르도록 했는데, 여러 경우가 있어 가독성이 매우 떨어지는 것 같습니다😭 그리고 다른 state가 변경되어 다시 렌더링 될 때도 같은 연산을 반복하게 되는 것 같아 추후 리팩토링시 개선이 필요해보입니다🥲`
- 멘토님께서 말씀해주신대로 인풋 창에 내용이 없으면 검사하지 않도록 했고, 인증 완료시 alert는 삭제했습니다!

Fix: 회원가입 유효성 검사 상태 버그 수정

---

client/src/atom/atom.js
client/src/components/Comment.js
client/src/pages/ArticleDetail.js

**atoms.js ArticleDetail.js**
- 좋아요 기능을 구현하였습니다.
- 어제 멘토님이 말씀하셨던 프로젝트 예정일정 레이아웃을 변경하였습니다~
- 비로그인 유저가 댓글 작성 버튼을 누르면, 로그인 후 다시 시도해달라는 알럿창이 뜰 수 있도록 수정하였습니다.
**Commnet.js**
유저의 프로필 이름 클릭시, 로그인한 상태의 유저라면 마이페이지로 이동하고 아니라면 프로필 상세페이지로 이동하도록 수정하여 구현하였습니다.

Feat: 좋아요 기능 구현

---

client/src/components/Calendar.js

Disign : 캘린더 범위 선택 삭제 및 오늘 날짜 색 변경

---

client/src/pages/Main.js

#122 
- 화면 너비에 따른 게시글 개수 설정 + 최소 개수 2개로 설정
- 화면 너비를 dom으로 접근해서 가져오고 싶었는데,,, 시간 내로 못해서 일단 수동으로 반응형 마진 값을 빼도록 했습니다,,😭
- 게시글 0개일 때 메시지 추가 
- 임시 로딩 메시지 css 수정

Fix: 메인 페이지 아티클 요청 개수 수정

---

client/src/components/InputBody.js
client/src/components/InputTitle.js
client/src/pages/ArticleEdit.js
client/src/pages/ArticleWrite.js

#119 
- 게시글 작성/ 수정 페이지에 공백만 입력했을 때도 유효성 검사를 하도록 추가했습니다.
- onblur 함수는 컴포넌트 내부에 선언되어 있어 페이지에 적어놓았던 코드는 삭제했습니다.
-----------------------------
글 작성, 수정에 들어가면 자동으로 본문에 오토포커스가 설정되어 있어서, 해제하려고 오후시간동안 찾아봤습니다..!
근데 이게 라이브러리라 해제하기가 쉽지 않은 것 같아요... ㅜㅜ 
autofocus 를 해제하도록 코드를 적어도 적용이 안되는 것 같아서 이 부분은 우선 넘어가야 할 것 같습니다ㅜㅜ..

feat: 게시글 작성/수정 페이지 유효성 검사 수정

---

client/src/pages/SignUp.js

닉네임 길이가 1자 이상일 경우만 검사하도록 했습니다.
비밀번호 확인 유효성 검사도 수정했습니다! 
state관리에 리팩토링이,,,,,,필요할것같아요ㅠ

Fix: 회원가입 페이지 닉네임/비밀번호 확인 유효성 검사 수정

---

client/src/components/Header.js
client/src/pages/ArticleWrite.js
client/src/pages/SignUp.js

#133 
- Signup
- 회원가입 버튼 눌렀을 때, 상태 초기화
- ArticleWrite, Header
- 헤더 아닌 글작성페이지에서 유효성검사상태 초기화

fix: 회원가입 버튼 눌렀을 때, 상태 초기화
